/* Autogenerated by bin2c */

#pragma once
#include <stdint.h>

extern uint8_t roboto_bold_ttf[];
extern uint32_t roboto_bold_ttf_size;

extern uint8_t roboto_regular_ttf[];
extern uint32_t roboto_regular_ttf_size;

extern uint8_t entypo_ttf[];
extern uint32_t entypo_ttf_size;

