#ifndef __GLPROCS_INCLUDE_H__
#define __GLPROCS_INCLUDE_H__

#include <SDL_opengl.h>

/*
struct glhelper
{
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLSHADERSOURCEPROC glShaderSource ;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv ;
PFNGLCOMPILESHADERPROC glCompileShader ;
PFNGLGETSHADERIVPROC glGetShaderiv ;
PFNGLUSEPROGRAMPROC glUseProgram ;
PFNGLUNIFORM1IPROC glUniform1i ;
PFNGLUNIFORM1FPROC glUniform1f ;
PFNGLUNIFORM2IPROC glUniform2i ;
PFNGLUNIFORM2FPROC glUniform2f ;
PFNGLUNIFORM3FPROC glUniform3f ;
PFNGLUNIFORM4FPROC glUniform4f ;
PFNGLUNIFORM4FVPROC glUniform4fv ;
PFNGLCREATEPROGRAMPROC glCreateProgram ;
PFNGLATTACHSHADERPROC glAttachShader ;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog ;
PFNGLLINKPROGRAMPROC glLinkProgram ;
PFNGLGETPROGRAMIVPROC glGetProgramiv ;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays ;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog ;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray ;
PFNGLBINDBUFFERPROC glBindBuffer ;
PFNGLGETATTRIBLOCATIONPROC  glGetAttribLocation ;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation ;
PFNGLGENBUFFERSPROC  glGenBuffers ;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
PFNGLBUFFERDATAPROC  glBufferData ;
PFNGLDISABLEVERTEXATTRIBARRAYPROC  glDisableVertexAttribArray ;
PFNGLENABLEVERTEXATTRIBARRAYPROC  glEnableVertexAttribArray ;
PFNGLGETBUFFERSUBDATAPROC  glGetBufferSubData ;
PFNGLVERTEXATTRIBPOINTERPROC  glVertexAttribPointer ;
PFNGLDELETEBUFFERSPROC  glDeleteBuffers ;
PFNGLBINDFRAMEBUFFERPROC  glBindFramebuffer ;
PFNGLBINDRENDERBUFFERPROC  glBindRenderbuffer ;
PFNGLRENDERBUFFERSTORAGEPROC  glRenderbufferStorage ;
PFNGLDELETEVERTEXARRAYSPROC  glDeleteVertexArrays ;
PFNGLDELETEPROGRAMPROC  glDeleteProgram ;
PFNGLDELETESHADERPROC  glDeleteShader ;
PFNGLGENRENDERBUFFERSPROC  glGenRenderbuffers ;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC  glRenderbufferStorageMultisample ;
PFNGLGENFRAMEBUFFERSPROC  glGenFramebuffers ;
PFNGLFRAMEBUFFERRENDERBUFFERPROC  glFramebufferRenderbuffer ;
PFNGLCHECKFRAMEBUFFERSTATUSPROC  glCheckFramebufferStatus ;
PFNGLDELETERENDERBUFFERSPROC  glDeleteRenderbuffers ;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer ;

PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
PFNGLUNIFORM2FVPROC glUniform2fv;
};

glhelper& glh();*/

#endif //__GLPROCS_INCLUDE_H__
